### ISSUE TITLE
get error with Q module

### ISSUE THREAD

**Issue by amigomcu** [bluetoother/cc-bnp#5]
hi all,
i try to run the example code ,but it get error with Q module.

c:\temp\cc-bnp\examples (master)
λ node ble_connect.js
DEPRECATION: Please use `require('serialport')` instead of `require('serialport').SerialPort`
undefined
c:\temp\node_modules\q\q.js:155
                throw e;
                ^

TypeError: Cannot read property 'GapDeviceInfo0' of undefined
    at c:\temp\cc-bnp\examples\ble_connect.js:18:26
    at c:\temp\node_modules\q\q.js:2052:17
    at runSingle (c:\temp\node_modules\q\q.js:137:13)
    at flush (c:\temp\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by hedywings** [comment]
Hi @amigomcu, this example is out of data, I have updated it, could you please try again? And If there is other problem, also please let me know, thank you!
